### PR TITLE
fix(examples): Dynamic Rollup Config Loading

### LINKED ISSUE #292: fix(examples): Load Rollup Config Based on L1 RPC Chain ID
**Description**

Dynamically load the rollup config from the superchain registry based on the chain id fetched from the specified l1 rpc in the `trusted-sync` example.

### PR DESCRIPTION
**Pull request by refcell**
**Description**

Updates the `trusted-sync` example to dynamically load the rollup config based on the l1 chain id.

In the future this will be upstreamed into the superchain-registry.

**Metadata**

Fixes #292.

### CODE REVIEW

File: examples/trusted-sync/src/main.rs [hunk 1]
```diff
@@ -37,10 +40,18 @@ async fn sync(cli_cfg: crate::cli::Cli) -> Result<()> {
     let beacon_url: String =
         cli_cfg.beacon_url.unwrap_or_else(|| std::env::var(BEACON_URL).unwrap());
 
+    // Fetch the Chain ID from the L1 provider.
+    let mut l1_provider = AlloyChainProvider::new_http(l1_rpc_url);
+    let chain_id = l1_provider.chain_id().await.expect("Failed to fetch chain ID from L1 provider");
+    // Get the rollup config for the given chain ID.
+    let available_configs =
+        &[OP_MAINNET_CONFIG, OP_SEPOLIA_CONFIG, BASE_MAINNET_CONFIG, BASE_SEPOLIA_CONFIG];
```
Comment (clabby) [inline examples/trusted-sync/src/main.rs:48]: Can we upstream a `config_by_chain_id` function in `superchain-registry` instead of this? It's also useful in the client program.

**Review by clabby — CHANGES_REQUESTED** [review]

**Review by clabby — APPROVED** [review]
